import { DocPage, Pending, type DocSection } from "../components/layout/DocPage";
import { siteConfig } from "../config";

/** Update whenever the substance of this policy changes. */
const EFFECTIVE = "2026-07-25";

const sections: readonly DocSection[] = [
  {
    id: "scope",
    nav: "what this covers",
    title: "this policy covers buying, activating, and supporting PatchTray Pro.",
    body: (
      <>
        <p>
          It describes what is stored when you purchase a PatchTray Pro license, activate it on a device, or
          contact support, and it covers this website. PatchTray Free does not require a purchase or an account.
        </p>
        <p>
          The audio you process, the plugins you load, and the presets you save stay on your computer. PatchTray
          does not upload them, and there is no cloud project or sync feature that would.
        </p>
      </>
    ),
  },
  {
    id: "purchase",
    nav: "purchase data",
    title: "the purchase record is an email address and Stripe identifiers.",
    body: (
      <>
        <p>
          Checkout runs on Stripe. Your card number never reaches PatchTray — Stripe collects and processes it
          directly. What comes back and is stored is the record needed to deliver and support a license:
        </p>
        <ul>
          <li>the email address you used at checkout, which is where the license key is sent;</li>
          <li>
            Stripe customer, Checkout Session, payment, and subscription identifiers, used to match a payment to a
            license;
          </li>
          <li>refund and dispute identifiers and their status, used to apply the outcome to the license.</li>
        </ul>
        <p>
          These identifiers are references to records held by Stripe, not copies of your payment details.
        </p>
      </>
    ),
  },
  {
    id: "licensing",
    nav: "device data",
    title: "activation stores which devices a license is running on, not who you are.",
    body: (
      <>
        <p>
          A Pro license may be activated on a limited number of devices — two for monthly, three for lifetime. To
          enforce that limit, and to issue the offline lease that lets PatchTray run without a connection, the
          licensing service stores:
        </p>
        <ul>
          <li>
            a <strong>pseudonymous device identifier</strong> generated by PatchTray. It identifies an
            installation to the licensing service and is not derived from your name or your account;
          </li>
          <li>
            <strong>activation metadata</strong> — when a device was activated, deactivated, or last validated,
            which plan it holds, and when its current lease expires;
          </li>
          <li>
            an <strong>IP-derived hash</strong> rather than your IP address, used to rate-limit and detect abuse
            of the licensing endpoints.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "operational",
    nav: "operational records",
    title: "licensing events are logged so problems can be investigated.",
    body: (
      <p>
        Activations, deactivations, key recoveries, refunds, disputes, and administrative actions are recorded as
        audit entries. They exist so support can answer &ldquo;what happened to my license,&rdquo; and so misuse
        can be identified. They are not used to profile you or to build an advertising audience.
      </p>
    ),
  },
  {
    id: "providers",
    nav: "service providers",
    title: "five providers process data on PatchTray's behalf.",
    body: (
      <>
        <ul className="legal-rows">
          <li>
            <strong>Stripe</strong>
            <span>Payment processing, subscription billing, refunds, and disputes.</span>
          </li>
          <li>
            <strong>Cloudflare</strong>
            <span>
              Hosts the licensing service and stores license, device, and audit records. Also provides the
              Turnstile bot check on the support form, which runs in your browser and reports to Cloudflare
              whether the request looks automated.
            </span>
          </li>
          <li>
            <strong>Resend</strong>
            <span>
              Delivers the license key, other transactional email, and messages sent through the support form.
            </span>
          </li>
          <li>
            <strong>Upstash</strong>
            <span>
              Holds the support form&rsquo;s rate-limiting counters, keyed by a hash of your IP address rather
              than the address itself.
            </span>
          </li>
          <li>
            <strong>Vercel</strong>
            <span>
              Hosts this website and provides its privacy-focused analytics and performance measurement, which
              record page views and timing rather than identifying individual visitors.
            </span>
          </li>
        </ul>
        <p>
          This site also loads its typefaces from Google Fonts, which means your browser contacts a Google server
          and Google receives the request&rsquo;s IP address.
        </p>
      </>
    ),
  },
  {
    id: "why",
    nav: "why it is processed",
    title: "each category exists for a stated purpose.",
    body: (
      <ul className="legal-rows">
        <li>
          <strong>fulfillment</strong>
          <span>Delivering the license you paid for to the address you gave at checkout.</span>
        </li>
        <li>
          <strong>entitlement</strong>
          <span>Confirming a license is valid and within its device limit when PatchTray activates or validates.</span>
        </li>
        <li>
          <strong>support</strong>
          <span>Finding your license from your purchase email so a request can be answered.</span>
        </li>
        <li>
          <strong>billing integrity</strong>
          <span>Applying refunds, disputes, and cancellations to the right license.</span>
        </li>
        <li>
          <strong>abuse prevention</strong>
          <span>Rate-limiting the licensing endpoints and detecting shared or automated misuse.</span>
        </li>
        <li>
          <strong>legal obligation</strong>
          <span>Keeping the transaction records that tax and accounting rules require.</span>
        </li>
      </ul>
    ),
  },
  {
    id: "retention",
    nav: "how long it is kept",
    title: "billing records outlive device records.",
    body: (
      <>
        <ul className="legal-rows">
          <li>
            <strong>billing and tax records</strong>
            <span>Kept for seven years after the transaction, as financial record-keeping rules require.</span>
          </li>
          <li>
            <strong>license and device records</strong>
            <span>
              Kept while the license is active and deleted twenty-four months after the last activation or
              validation.
            </span>
          </li>
          <li>
            <strong>audit records</strong>
            <span>Kept twenty-four months, then deleted.</span>
          </li>
          <li>
            <strong>support email</strong>
            <span>Kept twenty-four months after the conversation ends.</span>
          </li>
          <li>
            <strong>support rate limits</strong>
            <span>Hashed counters that expire one hour after the message that created them.</span>
          </li>
        </ul>
        <p>
          A revoked or refunded license keeps its billing record for the period above; its device records follow
          the licensing schedule.
        </p>
      </>
    ),
  },
  {
    id: "requests",
    nav: "your choices",
    title: "you can ask what is held, and ask for it to be deleted.",
    body: (
      <>
        <p>
          Write to <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a> from the address you
          used at checkout and say what you want. Depending on where you live, you may have rights to access,
          correct, export, or delete your personal information, and to object to some processing.
        </p>
        <p>
          Deleting a purchase record ends the license it supports — a deleted license cannot be recovered or
          reactivated, and the billing record is retained for the legally required period regardless. Ask for a
          copy of your data first if you want one.
        </p>
        <div className="legal-note">
          <p>
            Support will never ask you for a license key, a recovery code, a password, or card details. If you
            receive a message claiming to be PatchTray support and asking for any of those, it is not from us.
          </p>
        </div>
      </>
    ),
  },
  {
    id: "changes",
    nav: "changes",
    title: "material changes get a new effective date.",
    body: (
      <p>
        When this policy changes, the effective date at the top of the page changes with it. Continuing to use
        PatchTray after that date means the updated policy applies.
      </p>
    ),
  },
  {
    id: "contact",
    nav: "contact",
    title: "one address, for privacy questions and everything else.",
    body: (
      <>
        <p>
          Privacy questions, data requests, and security reports all go to the same place. The seller of record
          and the jurisdiction that governs this policy are stated in the{" "}
          <a href="/terms">terms</a>.
        </p>
        <div className="legal-contact">
          <p>
            privacy contact · <a href={`mailto:${siteConfig.supportEmail}`}>{siteConfig.supportEmail}</a>
          </p>
          <p>
            data controller · CyR1en (Ethan Bacurio)
          </p>
        </div>
      </>
    ),
  },
];

export function PrivacyPage() {
  return (
    <DocPage
      page="privacy"
      label="patchtray / privacy policy"
      heading={
        <>
          what is stored,
          <br />
          and for how long.
        </>
      }
      lead="PatchTray Pro needs an email address to send you a license and a device identifier to keep it inside its device limit. This page explains everything held beyond that, who processes it, and when it is deleted."
      effective={EFFECTIVE}
      sections={sections}
    />
  );
}
